### ISSUE TITLE
protobuf-protoc-bin does not follow Python Packaging strictly

### ISSUE THREAD

**Issue by liaoya** [RobertoRoos/protobuf-protoc-bin#16]
Now I use [uv](https://github.com/astral-sh/uv) to manage virtualenv. I can not run `uv pip install protobuf-protoc-bin` and I reported this issue [Directories in wheel scripts directory cause install error](https://github.com/astral-sh/uv/issues/9656) as `pip install protobuf-protoc-bin` works.

The maintainer of [uv](https://github.com/astral-sh/uv) talks with pip maintainer and they think `scripts directory is for files only`. You can find more the information in <https://github.com/pypa/packaging.python.org/pull/1673>

**Comment by RobertoRoos** [comment]
Thanks for the report, I had no idea I was doing something illegal. :p

But this is unfortunate, because `protoc` requires the `inlcude/` directory to be alongside the binary (for some reason).
See https://github.com/RobertoRoos/protobuf-protoc-bin/blob/main/setup.py#L71 and #18 .

I'll have to look around to see how else I might package up the `include` folder. Maybe a post-install script that will move the files from a `data/` directory.

**Comment by RobertoRoos** [comment]
I think I fixed it. CI is passing, but @liaoya do you think you'd have the opportunity to test an install on your system with `uv` directly from: https://github.com/RobertoRoos/protobuf-protoc-bin/tree/bugfix/include ?

I think it should be a matter of running
```
uv pip install git+https://github.com/RobertoRoos/protobuf-protoc-bin.git@bugfix/include
```

**Comment by liaoya** [comment]
@RobertoRoos Thank you for attention. I verified the following, both are OK. The problem is resolved.

- `uvx --from protobuf-protoc-bin protoc --version`
- `uv pip install git+https://github.com/RobertoRoos/protobuf-protoc-bin.git@bugfix/include`

**Comment by RobertoRoos** [comment]
Thanks for testing, I've merged the fix.
Unfortunately we cannot normally just re-publish existing releases, so we won't see any difference until the next protobuf release.
Fortunately, the `v29.1` build had failed last week, so I just re-triggered it and it should appear online in an hour or so.

**Comment by liaoya** [comment]
@RobertoRoos Yes, I verified `v29.1` is OK
![图片](https://github.com/user-attachments/assets/f0b573a1-7fb7-4fe1-b37b-d2cbe43bb52f)
